import type {
  PRView,
  IssueComment,
  InlineComment,
  NormalizedComment,
} from "./types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Bot detection
// ─────────────────────────────────────────────────────────────────────────────

const BOT_AUTHOR_PATTERNS = [
  "github-actions",
  "sonar",
  "sonarcloud",
  "cursor",
  "dependabot",
  "renovate",
  "codecov",
  "vercel",
  "netlify",
  "circleci",
  "travisci",
  "[bot]",
];

const BOT_BODY_PATTERNS = [
  "automatically",
  "this is an automated",
  "auto-generated",
  "generated by",
  "ci/cd",
  "coverage report",
  "deploy preview",
];

export function isLikelyBot(author: string, body: string): boolean {
  const authorLower = author.toLowerCase();
  const bodyLower = body.toLowerCase();

  // Check author name patterns
  for (const pattern of BOT_AUTHOR_PATTERNS) {
    if (authorLower.includes(pattern)) {
      return true;
    }
  }

  // Check body patterns
  for (const pattern of BOT_BODY_PATTERNS) {
    if (bodyLower.includes(pattern)) {
      return true;
    }
  }

  return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Normalize review bodies
// ─────────────────────────────────────────────────────────────────────────────

function normalizeReviews(prView: PRView): NormalizedComment[] {
  const results: NormalizedComment[] = [];

  for (const review of prView.reviews) {
    // Skip reviews without author
    if (!review.author) continue;

    // Keep review if it has body OR if state is CHANGES_REQUESTED (signal even without body)
    const hasBody = review.body && review.body.trim().length > 0;
    const isChangesRequested = review.state === "CHANGES_REQUESTED";

    if (!hasBody && !isChangesRequested) continue;

    const author = review.author.login;
    const body = review.body || "";

    results.push({
      id: `review-${review.submittedAt || Date.now()}-${author}`,
      kind: "review_body",
      author,
      createdAt: review.submittedAt || undefined,
      state: review.state,
      filePath: undefined,
      line: undefined,
      isResolved: undefined,
      body,
      url: prView.url,
      isBot: isLikelyBot(author, body),
    });
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// Normalize issue comments (PR conversation)
// ─────────────────────────────────────────────────────────────────────────────

function normalizeIssueComments(comments: IssueComment[]): NormalizedComment[] {
  const results: NormalizedComment[] = [];

  for (const comment of comments) {
    // Skip comments without user or body
    if (!comment.user) continue;
    const body = comment.body || "";
    if (!body.trim()) continue;

    const author = comment.user.login;

    results.push({
      id: `pr-comment-${comment.id}`,
      kind: "pr_comment",
      author,
      createdAt: comment.created_at,
      state: undefined,
      filePath: undefined,
      line: undefined,
      isResolved: undefined,
      body,
      url: comment.html_url,
      isBot: isLikelyBot(author, body),
    });
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// Normalize inline comments (review threads)
// ─────────────────────────────────────────────────────────────────────────────

function normalizeInlineComments(
  threads: InlineComment[]
): NormalizedComment[] {
  const results: NormalizedComment[] = [];

  for (const thread of threads) {
    for (const comment of thread.comments) {
      results.push({
        id: `inline-${comment.id}`,
        kind: "inline_comment",
        author: comment.author,
        createdAt: comment.createdAt,
        state: undefined,
        filePath: thread.path,
        line: thread.line ?? thread.originalLine ?? undefined,
        isResolved: thread.isResolved,
        body: comment.body,
        url: comment.url,
        isBot: isLikelyBot(comment.author, comment.body),
      });
    }
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main normalization function
// ─────────────────────────────────────────────────────────────────────────────

export function normalizeAll(
  prView: PRView,
  issueComments: IssueComment[],
  inlineComments: InlineComment[]
): NormalizedComment[] {
  const allComments: NormalizedComment[] = [
    ...normalizeReviews(prView),
    ...normalizeIssueComments(issueComments),
    ...normalizeInlineComments(inlineComments),
  ];

  // Sort by createdAt (oldest first)
  return allComments.sort((a, b) => {
    const aDate = a.createdAt ? new Date(a.createdAt).getTime() : 0;
    const bDate = b.createdAt ? new Date(b.createdAt).getTime() : 0;
    return aDate - bDate;
  });
}
